-- CUSTOMER CHURN ANALYTICS

CREATE OR REPLACE VIEW CUSTOMER_CHURN_ANALYTICS AS
SELECT
    GEOGRAPHY,
    ROUND(AVG(EXITED) * 100,2) AS CHURN_RATE,
    ROUND(AVG(AGE),2) AS AVG_AGE,
    ROUND(AVG(BALANCE),2) AS AVG_BALANCE,
    ROUND(AVG(CREDITSCORE),2) AS AVG_CREDITSCORE,
    COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMER360_MASTER
GROUP BY GEOGRAPHY;

----------------------------------------------------

-- CUSTOMER MARKETING ANALYTICS

CREATE OR REPLACE VIEW CUSTOMER_MARKETING_ANALYTICS AS
SELECT
    ROUND(AVG(CAMPAIGNS_RECEIVED),2) AS AVG_CAMPAIGNS,
    ROUND(AVG(RESPONSES),2) AS AVG_RESPONSES,
    ROUND(AVG(CONVERSIONS),2) AS AVG_CONVERSIONS,
    ROUND(AVG(TOTAL_SPEND),2) AS AVG_SPEND
FROM CUSTOMER360_MASTER;